import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import AppShell from "@/components/layouts/AppShell";
// import 'jsvectormap/dist/css/jsvectormap.css';


const fontMontserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "ULD UKDW",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="hydrated">
      <body className={`${fontMontserrat.className} antialiased`}>
        <AppShell>{children}</AppShell>
      </body>
    </html>

  );
}
